# Generated by Django 3.2.6 on 2021-08-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='origin_category',
        ),
        migrations.AlterField(
            model_name='main',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'В обработке'), (2, 'На рассмотрении'), (3, 'Отменен'), (4, 'Завершен')], default=1, null=True, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='main',
            name='сustomer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_customer', to='customer.customer', verbose_name='Клиент'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='OriginCategory',
        ),
    ]
